from __future__ import annotations

import json
from collections import Counter
from html import escape

from apksleuth.models import AnalysisReport, Finding, StringFinding


SUPPORTED_FORMATS = {"html", "json", "markdown", "summary", "summary-json"}
SUPPORTED_LANGUAGES = {"en", "zh"}

LABELS = {
    "en": {
        "report_title": "ApkSleuth Report",
        "brief_title": "ApkSleuth Brief Report",
        "generated": "Generated",
        "tool": "Tool",
        "verdict": "Verdict",
        "overall": "Overall",
        "high_findings": "High findings",
        "medium_findings": "Medium findings",
        "main_risk_drivers": "Main risk drivers",
        "high_confidence_signals": "High-confidence findings",
        "review_needed_signals": "Review-needed findings",
        "apk": "APK",
        "apk_summary": "APK Summary",
        "file": "File",
        "size": "Size",
        "package": "Package",
        "app": "App",
        "app_name": "App Name",
        "version": "Version",
        "sdk": "SDK",
        "min": "min",
        "target": "target",
        "compile": "compile",
        "key_signals": "Key Security Signals",
        "debuggable": "Debuggable",
        "allow_backup": "Allow Backup",
        "cleartext_traffic": "Cleartext Traffic",
        "network_security_config": "Network Security Config",
        "exported_components": "Exported Components",
        "high_risk_permissions": "High-Risk Permissions",
        "http_urls": "HTTP URLs",
        "possible_secrets": "Possible Secrets",
        "native_libraries": "Native Libraries",
        "sdks": "SDKs",
        "packer_hints": "Packer Hints",
        "signature_schemes": "Signature Schemes",
        "top_findings": "Top Findings",
        "exported_component_samples": "Exported Component Samples",
        "http_url_samples": "HTTP URL Samples",
        "possible_secret_samples": "Possible Secret Samples",
        "priority_recommendations": "Priority Recommendations",
        "analysis_notes": "Analysis Notes",
        "risk_summary": "Risk Summary",
        "manifest_findings": "Manifest Findings",
        "manifest_signals": "Manifest Signals",
        "permissions": "Permissions",
        "network_artifacts": "Network Artifacts",
        "certificate": "Certificate",
        "sdk_fingerprints": "SDK Fingerprints",
        "packer_fingerprints": "Packer Fingerprints",
        "recommendations": "Recommendations",
        "field": "Field",
        "value": "Value",
        "severity": "Severity",
        "confidence": "Confidence",
        "count": "Count",
        "rule": "Rule",
        "evidence": "Evidence",
        "review_hint": "Review Hint",
        "level": "Level",
        "permission": "Permission",
        "recommendation": "Recommendation",
        "type": "Type",
        "name": "Name",
        "exported": "Exported",
        "source": "Source",
        "subject": "Subject",
        "issuer": "Issuer",
        "valid_until": "Valid Until",
        "signature_file": "Signature File",
        "abi": "ABI",
        "library": "Library",
        "stripped": "Stripped",
        "matched_patterns": "Matched Patterns",
        "application_class": "Application Class",
        "deep_links": "Deep Links",
        "provider_authorities": "Provider Authorities",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Info",
        "secrets": "Secrets",
        "native_libs": "Native Libs",
        "packers": "Packers",
        "unknown": "unknown",
        "none": "none",
        "bytes": "bytes",
        "no_risks": "No major risk findings were generated by the built-in rules.",
        "no_permissions": "No permissions were found.",
        "no_exported": "No exported or implicitly exported components were detected.",
        "no_network": "No URLs, IPs, or emails were found.",
        "no_secrets": "No possible secrets were found.",
        "no_native": "No native libraries were found.",
        "no_sdks": "No known SDK fingerprints were detected.",
        "no_packers": "No known packer fingerprints were detected.",
        "no_recommendations": "No rule-specific recommendations were generated.",
        "truncated": "Report output was truncated for readability. JSON contains all collected values.",
        "sig_schemes": "Signature schemes",
        "html_title": "ApkSleuth Report",
        "search_findings": "Search risk findings",
        "search_placeholder": "Search rule, evidence, component, URL...",
        "severity_filter": "Severity filter",
        "all": "All",
        "matching_findings": "Matching risk findings",
        "no_matching_findings": "No matching risk findings.",
    },
    "zh": {
        "report_title": "ApkSleuth 分析报告",
        "brief_title": "ApkSleuth 简报",
        "generated": "生成时间",
        "tool": "工具",
        "verdict": "结论",
        "overall": "总体判断",
        "high_findings": "高危风险",
        "medium_findings": "中危风险",
        "main_risk_drivers": "主要风险来源",
        "high_confidence_signals": "高置信风险项",
        "review_needed_signals": "需复核风险项",
        "apk": "APK",
        "apk_summary": "APK 概览",
        "file": "文件",
        "size": "大小",
        "package": "包名",
        "app": "应用",
        "app_name": "应用名",
        "version": "版本",
        "sdk": "SDK",
        "min": "最低",
        "target": "目标",
        "compile": "编译",
        "key_signals": "关键安全信号",
        "debuggable": "Debuggable",
        "allow_backup": "允许备份",
        "cleartext_traffic": "允许明文流量",
        "network_security_config": "网络安全配置",
        "exported_components": "导出组件",
        "high_risk_permissions": "高危权限",
        "http_urls": "HTTP 明文 URL",
        "possible_secrets": "疑似密钥",
        "native_libraries": "Native 库",
        "sdks": "SDK",
        "packer_hints": "加固/混淆线索",
        "signature_schemes": "签名方案",
        "top_findings": "主要风险项",
        "exported_component_samples": "导出组件样例",
        "http_url_samples": "HTTP URL 样例",
        "possible_secret_samples": "疑似密钥样例",
        "priority_recommendations": "优先修复建议",
        "analysis_notes": "分析说明",
        "risk_summary": "风险概览",
        "manifest_findings": "Manifest 检查",
        "manifest_signals": "Manifest 信号",
        "permissions": "权限",
        "network_artifacts": "网络痕迹",
        "certificate": "证书",
        "sdk_fingerprints": "SDK 指纹",
        "packer_fingerprints": "加固/混淆指纹",
        "recommendations": "修复建议",
        "field": "字段",
        "value": "值",
        "severity": "等级",
        "confidence": "可信度",
        "count": "数量",
        "rule": "规则",
        "evidence": "证据",
        "review_hint": "复核提示",
        "level": "级别",
        "permission": "权限",
        "recommendation": "建议",
        "type": "类型",
        "name": "名称",
        "exported": "导出",
        "source": "来源",
        "subject": "主体",
        "issuer": "颁发者",
        "valid_until": "有效期至",
        "signature_file": "签名文件",
        "abi": "架构",
        "library": "库文件",
        "stripped": "是否 Strip",
        "matched_patterns": "命中特征",
        "application_class": "Application 类",
        "deep_links": "Deep Link",
        "provider_authorities": "Provider Authority",
        "high": "高危",
        "medium": "中危",
        "low": "低危",
        "info": "信息",
        "secrets": "密钥",
        "native_libs": "Native 库",
        "packers": "加固",
        "unknown": "未知",
        "none": "无",
        "bytes": "字节",
        "no_risks": "内置规则未发现风险项。",
        "no_permissions": "未发现权限。",
        "no_exported": "未发现导出或隐式导出组件。",
        "no_network": "未发现 URL、IP 或邮箱。",
        "no_secrets": "未发现疑似密钥。",
        "no_native": "未发现 Native 库。",
        "no_sdks": "未命中已知 SDK 指纹。",
        "no_packers": "未命中已知加固/混淆指纹。",
        "no_recommendations": "未生成规则级修复建议。",
        "truncated": "为提升可读性，报告内容已截断；完整数据请查看 JSON。",
        "sig_schemes": "签名方案",
        "html_title": "ApkSleuth 分析报告",
        "search_findings": "搜索风险项",
        "search_placeholder": "搜索规则、证据、组件、URL...",
        "severity_filter": "等级筛选",
        "all": "全部",
        "matching_findings": "匹配风险项",
        "no_matching_findings": "没有匹配的风险项。",
    },
}

FINDING_TITLES_ZH = {
    "android-debuggable-enabled": "启用了 Debuggable",
    "android-allow-backup-enabled": "允许 ADB 备份",
    "cleartext-traffic-enabled": "允许明文网络流量",
    "exported-component": "导出组件",
    "exported-provider": "导出 Provider 未受权限保护",
    "exported-provider-partial-permission": "导出 Provider 使用读写权限分离",
    "exported-provider-grant-uri": "导出 Provider 允许 URI 授权",
    "exported-service": "导出 Service 未受权限保护",
    "exported-receiver": "导出 Receiver 未受权限保护",
    "exported-activity": "导出 Activity 未受权限保护",
    "exported-deep-link-activity": "导出 Deep Link Activity",
    "exported-protected-component": "受权限保护的导出组件",
    "exported-media-component": "导出媒体控制组件",
    "exported-quick-settings-tile": "导出快捷设置 Tile 服务",
    "exported-autofill-service": "导出 Autofill 服务",
    "exported-documents-provider": "导出 DocumentsProvider",
    "exported-file-provider": "导出 FileProvider 未受权限保护",
    "exported-share-target-activity": "导出分享入口 Activity",
    "exported-file-handler-activity": "导出文件处理 Activity",
    "exported-custom-tabs-service": "导出 Custom Tabs 服务",
    "exported-car-service": "导出车载集成服务",
    "exported-widget-receiver": "导出 App Widget Receiver",
    "implicit-exported-component": "隐式导出组件",
    "high-risk-permission": "高危权限",
    "hardcoded-secret": "疑似硬编码密钥",
    "http-url-found": "发现 HTTP 明文 URL",
    "debug-certificate": "Debug 证书",
}

FINDING_RECOMMENDATIONS_ZH = {
    "android-debuggable-enabled": "Release 构建中关闭 android:debuggable。",
    "android-allow-backup-enabled": "除非确有必要且已做保护，否则设置 android:allowBackup=\"false\"。",
    "cleartext-traffic-enabled": "使用 HTTPS，并通过 network security config 限制明文流量。",
    "exported-component": "明确设置 android:exported，并为可被外部访问的组件增加权限保护。",
    "exported-provider": "设置 android:exported=\"false\"，或使用 signature 级权限保护 Provider。",
    "exported-provider-partial-permission": "确认 readPermission 和 writePermission 的保护级别足以保护暴露的数据和操作。",
    "exported-provider-grant-uri": "复核 Provider path 范围，只对预期文件或记录授予 URI 权限。",
    "exported-service": "设置 android:exported=\"false\"，或为 Service 增加 signature 级权限。",
    "exported-receiver": "限制 Receiver 暴露面，校验外部广播，或为外部广播增加权限要求。",
    "exported-activity": "除非该 Activity 是公开入口，否则设置 android:exported=\"false\"，并校验所有 Intent 输入。",
    "exported-deep-link-activity": "校验所有 Deep Link 参数，敏感流程必须鉴权，并尽量限制 exported 暴露面。",
    "exported-protected-component": "确认权限 protectionLevel，只有确需外部访问时才保持 exported。",
    "exported-media-component": "确认该组件只处理标准媒体控制 Intent，并校验外部输入。",
    "exported-quick-settings-tile": "确认 Tile 服务只响应系统绑定和明确用户操作，不在点击前执行敏感逻辑。",
    "exported-autofill-service": "确认服务受 Autofill 框架权限保护，并校验所有填充请求。",
    "exported-documents-provider": "确认文档根目录、URI grant 和访问控制只暴露用户授权文件。",
    "exported-file-provider": "除非确需公开访问，否则设置 android:exported=\"false\"，并限制 provider paths 和 URI grant。",
    "exported-share-target-activity": "校验分享 MIME 类型、URI 权限、文件大小和内容解析逻辑。",
    "exported-file-handler-activity": "校验 URI scheme、MIME 类型、文件大小和解析器行为。",
    "exported-custom-tabs-service": "确认 Custom Tabs 暴露的方法不会泄露浏览状态或触发特权操作。",
    "exported-car-service": "校验 Android Auto / 车载入口，避免无用户确认执行敏感行为。",
    "exported-widget-receiver": "校验 Widget 广播 action 和 extras，忽略非预期外部广播。",
    "implicit-exported-component": "显式设置 android:exported；除非确需外部访问，否则设置为 false。",
    "high-risk-permission": "确认该权限是否为核心功能必需；不必要时移除或改用更低敏感度能力。",
    "hardcoded-secret": "不要在 APK 中硬编码密钥；确认泄露后应轮换凭据并迁移到服务端。",
    "http-url-found": "优先使用 HTTPS，移除无用的调试、测试或明文接口地址。",
    "debug-certificate": "Release 包应使用受保护的正式签名证书。",
}

FINDING_REVIEW_HINTS_ZH = {
    "android-debuggable-enabled": "确认该 APK 是否为 Release 构建；正式分发包不应启用 debuggable。",
    "android-allow-backup-enabled": "复核敏感本地数据是否可能被备份或恢复，并结合目标 Android 版本确认行为。",
    "cleartext-traffic-enabled": "检查 network security config 和运行时接口，确认生产环境是否存在可达明文流量。",
    "exported-provider": "复核 Provider authorities、path permissions、grantUriPermissions 和 query/insert/update/delete 处理逻辑。",
    "exported-provider-partial-permission": "复核 readPermission/writePermission 的 protectionLevel，确认不存在未受保护的读写操作。",
    "exported-provider-grant-uri": "复核 path-permission、meta-data 和 provider paths，确认 URI grant 不会暴露过宽的私有数据。",
    "exported-service": "复核 Service 入口、Intent 处理、Binder 暴露面以及调用方鉴权。",
    "exported-receiver": "复核接收的广播 action，确保不可信 extras 不能触发敏感行为。",
    "exported-activity": "确认该 Activity 是否有意作为公开入口，并校验所有 Intent extras 和 data URI。",
    "exported-deep-link-activity": "复核 scheme、host、path 过滤规则、鉴权要求和所有 Deep Link 参数校验。",
    "exported-media-component": "复核 Intent 处理代码，确保只接受预期的标准媒体控制动作。",
    "exported-protected-component": "确认权限 protectionLevel；normal 或 dangerous 级权限可能不足以保护敏感导出组件。",
    "exported-quick-settings-tile": "复核 Tile 点击处理，确保没有用户意图时不会执行敏感操作。",
    "exported-autofill-service": "复核 Autofill 数据集处理，确认只有可信框架调用能访问敏感数据。",
    "exported-documents-provider": "复核 query/openDocument/deleteDocument 处理逻辑，确认访问范围受用户授权限制。",
    "exported-file-provider": "复核 provider paths、URI grant、MIME 处理以及所有 openFile/openAssetFile 路径。",
    "exported-share-target-activity": "复核 ACTION_SEND/ACTION_SEND_MULTIPLE 处理，拒绝非预期 MIME 类型或超大输入。",
    "exported-file-handler-activity": "复核 ACTION_VIEW 对 file/content URI 的处理，确认解析外部内容不会触发不安全文件访问。",
    "exported-custom-tabs-service": "复核 Custom Tabs 绑定行为，确认调用方不能访问敏感浏览器内部状态。",
    "exported-car-service": "复核 Android Auto 会话处理、导航 Intent 和对调用方的假设。",
    "exported-widget-receiver": "复核 Widget action 处理，忽略非预期广播或不可信 extras。",
    "implicit-exported-component": "确认目标平台行为，并显式设置 android:exported 以避免暴露面不一致。",
    "high-risk-permission": "确认权限是否为核心功能必需，并通过运行时授权流程或功能开关限制使用。",
    "hardcoded-secret": "确认该值是否为有效凭据或 Token；如确认泄露，应立即轮换。",
    "http-url-found": "确认该 URL 是否在生产代码中可达；静态字符串可能包含历史、插件或测试端点。",
    "debug-certificate": "确认 APK 是否不是 Release 产物；生产分发包不应使用 Debug 证书。",
}


def render_report(report: AnalysisReport, output_format: str, language: str = "zh") -> str:
    normalized = output_format.lower()
    lang = _normalize_language(language)
    if normalized == "json":
        return json.dumps(report.to_dict(), ensure_ascii=False, indent=2)
    if normalized == "markdown":
        return render_markdown(report, lang)
    if normalized == "summary":
        return render_summary(report, lang)
    if normalized == "summary-json":
        return render_summary_json(report, lang)
    if normalized == "html":
        return render_html(report, lang)
    raise ValueError(f"Unsupported report format: {output_format}")


def render_markdown(report: AnalysisReport, language: str = "zh") -> str:
    lang = _normalize_language(language)
    lines: list[str] = []
    lines.append(f"# {_label(lang, 'report_title')}")
    lines.append("")
    lines.append(f"{_label(lang, 'generated')}: `{report.generated_at}`")
    lines.append(f"{_label(lang, 'tool')}: `{report.tool_name} v{report.tool_version}`")
    lines.append("")

    lines.extend(_apk_summary(report, lang))
    lines.extend(_risk_summary(report, lang))
    lines.extend(_manifest_findings(report, lang))
    lines.extend(_permissions(report, lang))
    lines.extend(_exported_components(report, lang))
    lines.extend(_strings(report, lang))
    lines.extend(_certificate(report, lang))
    lines.extend(_native_libraries(report, lang))
    lines.extend(_fingerprints(report, lang))
    lines.extend(_recommendations(report.findings, lang))

    if report.errors:
        lines.append(f"## {_label(lang, 'analysis_notes')}")
        lines.append("")
        for error in report.errors:
            lines.append(f"- {error}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_summary(report: AnalysisReport, language: str = "zh") -> str:
    lang = _normalize_language(language)
    apk = report.apk
    manifest = report.manifest
    counts = report.statistics.get("findings_by_severity", {}) if report.statistics else {}
    confidence = report.statistics.get("findings_by_confidence", {}) if report.statistics else {}
    exported = _exported_components_list(report)
    high_permissions = [item.name for item in report.permissions if item.level == "high"]
    urls = [item for item in report.strings if item.type == "url"]
    http_urls = [item for item in urls if item.value.lower().startswith("http://")]
    secrets = [item for item in report.strings if item.type in {"possible_secret", "jwt"}]
    deep_links = _group_deep_links(manifest.deep_links)

    lines = [
        f"# {_label(lang, 'brief_title')}",
        "",
        f"## {_label(lang, 'verdict')}",
        "",
        f"- {_label(lang, 'overall')}: {_overall_verdict(report, lang)}",
        f"- {_label(lang, 'high_findings')}: {counts.get('high', 0)}",
        f"- {_label(lang, 'medium_findings')}: {counts.get('medium', 0)}",
        f"- {_label(lang, 'high_confidence_signals')}: {confidence.get('high', 0)}",
        f"- {_label(lang, 'review_needed_signals')}: {confidence.get('medium', 0)}",
        f"- {_label(lang, 'main_risk_drivers')}: {_join_finding_drivers(report.findings, language=lang)}",
        "",
        f"## {_label(lang, 'apk')}",
        "",
        f"- {_label(lang, 'file')}: {apk.file_name}",
        f"- {_label(lang, 'app')}: {_plain(apk.app_name) or _label(lang, 'unknown')}",
        f"- {_label(lang, 'package')}: {_plain(apk.package_name) or _label(lang, 'unknown')}",
        f"- {_label(lang, 'version')}: {_plain(apk.version_name) or _label(lang, 'unknown')} ({_plain(apk.version_code) or _label(lang, 'unknown')})",
        f"- {_label(lang, 'size')}: {_format_size(apk.file_size, lang)}",
        f"- {_label(lang, 'sdk')}: {_label(lang, 'min')} {_plain(apk.min_sdk) or _label(lang, 'unknown')}, {_label(lang, 'target')} {_plain(apk.target_sdk) or _label(lang, 'unknown')}, {_label(lang, 'compile')} {_plain(apk.compile_sdk) or _label(lang, 'unknown')}",
        f"- SHA256: {apk.hashes.sha256}",
        "",
        f"## {_label(lang, 'key_signals')}",
        "",
        f"- {_label(lang, 'debuggable')}: {manifest.debuggable}",
        f"- {_label(lang, 'allow_backup')}: {manifest.allow_backup}",
        f"- {_label(lang, 'cleartext_traffic')}: {manifest.uses_cleartext_traffic}",
        f"- {_label(lang, 'network_security_config')}: {_plain(manifest.network_security_config) or _label(lang, 'none')}",
        f"- {_label(lang, 'exported_components')}: {len(exported)}",
        f"- {_label(lang, 'high_risk_permissions')}: {len(high_permissions)}",
        f"- {_label(lang, 'http_urls')}: {len(http_urls)}",
        f"- {_label(lang, 'possible_secrets')}: {len(secrets)}",
        f"- {_label(lang, 'native_libraries')}: {len(report.native_libraries)}",
        f"- {_label(lang, 'sdks')}: {_join_names([sdk.name for sdk in report.sdks], lang)}",
        f"- {_label(lang, 'packer_hints')}: {_join_names([packer.name for packer in report.packers], lang)}",
        f"- {_label(lang, 'signature_schemes')}: {_join_names(report.certificate.schemes, lang)}",
        "",
    ]

    lines.extend(_summary_list(_label(lang, 'top_findings'), _format_top_findings(report.findings, language=lang), lang))
    lines.extend(_summary_list(_label(lang, 'high_risk_permissions'), high_permissions[:12], lang))
    lines.extend(_summary_list(_label(lang, 'exported_component_samples'), [f"{item.type}: {item.name}" for item in exported[:12]], lang))
    lines.extend(_summary_list(_label(lang, 'deep_links'), [_format_deep_link_group(item) for item in deep_links[:12]], lang))
    lines.extend(_summary_list(_label(lang, 'http_url_samples'), [f"{item.value} ({item.source})" for item in http_urls[:12]], lang))
    lines.extend(_summary_list(_label(lang, 'possible_secret_samples'), [f"{item.value} ({item.source})" for item in secrets[:8]], lang))
    lines.extend(_summary_list(_label(lang, 'priority_recommendations'), _top_recommendations(report.findings, limit=8, language=lang), lang))

    if report.errors:
        lines.extend(_summary_list(_label(lang, 'analysis_notes'), report.errors, lang))

    return "\n".join(lines).rstrip() + "\n"


def render_summary_json(report: AnalysisReport, language: str = "zh") -> str:
    lang = _normalize_language(language)
    return json.dumps(_summary_payload(report, lang), ensure_ascii=False, indent=2)


def _summary_payload(report: AnalysisReport, language: str) -> dict[str, object]:
    apk = report.apk
    counts = report.statistics.get("findings_by_severity", {}) if report.statistics else {}
    confidence = report.statistics.get("findings_by_confidence", {}) if report.statistics else {}
    exported = _exported_components_list(report)
    high_permissions = [item.name for item in report.permissions if item.level == "high"]
    http_urls = [item for item in report.strings if item.type == "url" and item.value.lower().startswith("http://")]
    secrets = [item for item in report.strings if item.type in {"possible_secret", "jwt"}]
    finding_counts = Counter(item.id for item in report.findings)
    deep_links = _group_deep_links(report.manifest.deep_links)

    top_findings = []
    for finding_id, count, finding in _ranked_finding_groups(report.findings, limit=12):
        top_findings.append(
            {
                "id": finding.id,
                "title": _finding_title(finding, language),
                "severity": finding.severity,
                "severity_label": _severity_label(finding.severity, language),
                "confidence": finding.confidence,
                "confidence_label": _confidence_label(finding.confidence, language),
                "count": count,
                "sample_evidence": _finding_evidence(finding, language),
                "recommendation": _finding_recommendation(finding, language),
                "review_hint": _finding_review_hint(finding, language),
            }
        )

    return {
        "language": language,
        "tool": {
            "name": report.tool_name,
            "version": report.tool_version,
            "generated_at": report.generated_at,
        },
        "apk": {
            "file_name": apk.file_name,
            "app_name": apk.app_name,
            "package_name": apk.package_name,
            "version_name": apk.version_name,
            "version_code": apk.version_code,
            "file_size": apk.file_size,
            "file_size_display": _format_size(apk.file_size, language),
            "min_sdk": apk.min_sdk,
            "target_sdk": apk.target_sdk,
            "compile_sdk": apk.compile_sdk,
            "sha256": apk.hashes.sha256,
        },
        "verdict": {
            "overall": _overall_verdict(report, language),
            "risk_drivers": {finding_id: count for finding_id, count, _ in _ranked_finding_groups(report.findings, limit=len(finding_counts))},
        },
        "risk": {
            "total": len(report.findings),
            "high": counts.get("high", 0),
            "medium": counts.get("medium", 0),
            "low": counts.get("low", 0),
            "info": counts.get("info", 0),
        },
        "confidence": {
            "high": confidence.get("high", 0),
            "medium": confidence.get("medium", 0),
            "low": confidence.get("low", 0),
        },
        "key_signals": {
            "debuggable": report.manifest.debuggable,
            "allow_backup": report.manifest.allow_backup,
            "uses_cleartext_traffic": report.manifest.uses_cleartext_traffic,
            "network_security_config": report.manifest.network_security_config,
            "exported_components": len(exported),
            "high_risk_permissions": len(high_permissions),
            "http_urls": len(http_urls),
            "possible_secrets": len(secrets),
            "native_libraries": len(report.native_libraries),
            "signature_schemes": report.certificate.schemes,
        },
        "top_findings": top_findings,
        "high_risk_permissions": high_permissions[:30],
        "exported_component_samples": [
            {
                "type": item.type,
                "name": item.name,
                "permission": item.permission,
                "read_permission": item.read_permission,
                "write_permission": item.write_permission,
                "authorities": item.authorities,
                "grant_uri_permissions": item.grant_uri_permissions,
                "exported": item.exported,
            }
            for item in exported[:30]
        ],
        "deep_link_samples": deep_links[:30],
        "http_url_samples": [
            {"value": item.value, "source": item.source, "severity": item.severity} for item in http_urls[:30]
        ],
        "possible_secret_samples": [
            {"type": item.type, "value": item.value, "source": item.source} for item in secrets[:12]
        ],
        "sdks": [
            {"name": item.name, "type": item.type, "matched_patterns": item.matched_patterns} for item in report.sdks
        ],
        "packers": [
            {"name": item.name, "confidence": item.confidence, "matched_patterns": item.matched_patterns}
            for item in report.packers
        ],
        "recommendations": _top_recommendations(report.findings, limit=10, language=language),
        "errors": report.errors,
    }


def render_html(report: AnalysisReport, language: str = "zh") -> str:
    lang = _normalize_language(language)
    apk = report.apk
    counts = report.statistics.get("findings_by_severity", {}) if report.statistics else {}
    exported = _exported_components_list(report)
    high_permissions = [item.name for item in report.permissions if item.level == "high"]
    http_urls = [item for item in report.strings if item.type == "url" and item.value.lower().startswith("http://")]
    secrets = [item for item in report.strings if item.type in {"possible_secret", "jwt"}]

    cards = [
        (_label(lang, "high"), counts.get("high", 0), "high"),
        (_label(lang, "medium"), counts.get("medium", 0), "medium"),
        (_label(lang, "exported"), len(exported), "high" if exported else "ok"),
        (_label(lang, "http_urls"), len(http_urls), "medium" if http_urls else "ok"),
        (_label(lang, "secrets"), len(secrets), "high" if secrets else "ok"),
        (_label(lang, "native_libs"), len(report.native_libraries), "info"),
    ]
    sdk_text = f"{_label(lang, 'min')} {apk.min_sdk}, {_label(lang, 'target')} {apk.target_sdk}, {_label(lang, 'compile')} {apk.compile_sdk}"

    return f"""<!doctype html>
<html lang=\"{_html('zh-CN' if lang == 'zh' else 'en')}\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>{_html(_label(lang, 'html_title'))} - {_html(apk.file_name)}</title>
  <style>
    :root {{ color-scheme: light dark; --bg: #0f172a; --panel: #111827; --muted: #94a3b8; --text: #e5e7eb; --line: #243244; --high: #ef4444; --medium: #f59e0b; --ok: #22c55e; --info: #38bdf8; }}
    body {{ margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: linear-gradient(135deg, #0f172a, #111827 55%, #172554); color: var(--text); }}
    main {{ max-width: 1180px; margin: 0 auto; padding: 32px 18px 64px; }}
    h1 {{ margin: 0 0 8px; font-size: clamp(2rem, 5vw, 4rem); letter-spacing: -0.05em; }}
    h2 {{ margin-top: 32px; border-bottom: 1px solid var(--line); padding-bottom: 10px; }}
    .muted {{ color: var(--muted); }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(155px, 1fr)); gap: 14px; margin: 24px 0; }}
    .card {{ background: rgba(17, 24, 39, 0.82); border: 1px solid var(--line); border-radius: 18px; padding: 18px; box-shadow: 0 20px 45px rgba(0,0,0,.18); }}
    .card strong {{ display: block; font-size: 2rem; margin-top: 6px; }}
    .high strong, .high .badge {{ color: var(--high); }} .medium strong, .medium .badge {{ color: var(--medium); }} .ok strong, .ok .badge {{ color: var(--ok); }} .info strong, .info .badge {{ color: var(--info); }}
    table {{ width: 100%; border-collapse: collapse; overflow: hidden; border-radius: 14px; background: rgba(17, 24, 39, 0.72); }}
    th, td {{ text-align: left; padding: 11px 12px; border-bottom: 1px solid var(--line); vertical-align: top; }}
    th {{ color: #cbd5e1; background: rgba(15, 23, 42, 0.7); }}
    code {{ color: #bae6fd; word-break: break-all; }}
    ul {{ padding-left: 1.2rem; }}
    li {{ margin: 7px 0; }}
    .section {{ background: rgba(15, 23, 42, 0.45); border: 1px solid rgba(148,163,184,.18); border-radius: 20px; padding: 18px; margin-top: 16px; }}
    details.section > summary {{ cursor: pointer; list-style-position: outside; font-size: 1.35rem; font-weight: 800; padding: 4px 0 12px; }}
    details.section > summary::marker {{ color: #38bdf8; }}
    details.section[open] > summary {{ border-bottom: 1px solid var(--line); margin-bottom: 14px; }}
    .controls {{ display: flex; flex-wrap: wrap; gap: 12px; align-items: end; margin: 0 0 14px; }}
    .control {{ display: grid; gap: 6px; min-width: min(100%, 230px); }}
    .control label {{ color: #cbd5e1; font-size: .9rem; }}
    .control input, .control select {{ border: 1px solid var(--line); border-radius: 12px; background: rgba(15,23,42,.72); color: var(--text); padding: 10px 12px; }}
    .finding-meta {{ color: var(--muted); margin-left: auto; padding: 10px 0; }}
    tr[hidden], .hidden {{ display: none !important; }}
  </style>
</head>
<body>
<main>
  <p class=\"muted\">{_html(report.tool_name)} v{_html(report.tool_version)} | {_html(report.generated_at)}</p>
  <h1>{_html(apk.app_name or apk.file_name)}</h1>
  <p class=\"muted\"><code>{_html(apk.package_name)}</code> | {_html(_label(lang, 'version'))} {_html(apk.version_name)} ({_html(apk.version_code)}) | {_html(_format_size(apk.file_size, lang))}</p>
  <div class=\"grid\">{''.join(_html_card(label, value, tone) for label, value, tone in cards)}</div>
  {_html_section(_label(lang, 'apk_summary'), _html_key_values([
        (_label(lang, 'file'), apk.file_name), (_label(lang, 'app_name'), apk.app_name), (_label(lang, 'package'), apk.package_name), (_label(lang, 'version'), f'{apk.version_name} ({apk.version_code})'),
        (_label(lang, 'sdk'), sdk_text), ('SHA256', apk.hashes.sha256),
    ]), open_section=True)}
  {_html_section(_label(lang, 'risk_summary'), _html_findings(report.findings, lang), open_section=True)}
  {_html_section(_label(lang, 'manifest_signals'), _html_key_values([
        (_label(lang, 'debuggable'), report.manifest.debuggable), (_label(lang, 'allow_backup'), report.manifest.allow_backup), (_label(lang, 'cleartext_traffic'), report.manifest.uses_cleartext_traffic),
        (_label(lang, 'network_security_config'), report.manifest.network_security_config), (_label(lang, 'application_class'), report.manifest.application_class),
    ]), open_section=False)}
  {_html_section(_label(lang, 'exported_component_samples'), _html_list([f'{item.type}: {item.name}' for item in exported[:40]], _label(lang, 'no_exported')), open_section=False)}
  {_html_section(_label(lang, 'deep_links'), _html_list([_format_deep_link_group(item) for item in _group_deep_links(report.manifest.deep_links)[:40]], _label(lang, 'none')), open_section=False)}
  {_html_section(_label(lang, 'high_risk_permissions'), _html_list(high_permissions, _label(lang, 'no_permissions')), open_section=False)}
  {_html_section(_label(lang, 'http_url_samples'), _html_list([f'{item.value} ({item.source})' for item in http_urls[:40]], _label(lang, 'no_network')), open_section=False)}
  {_html_section(_label(lang, 'sdk_fingerprints'), _html_key_values([
        (_label(lang, 'sdks'), _join_names([sdk.name for sdk in report.sdks], lang)), (_label(lang, 'packers'), _join_names([packer.name for packer in report.packers], lang)), (_label(lang, 'signature_schemes'), _join_names(report.certificate.schemes, lang)),
    ]), open_section=False)}
</main>
{_html_filter_script()}
</body>
</html>
"""


def _apk_summary(report: AnalysisReport, language: str) -> list[str]:
    apk = report.apk
    return [
        f"## {_label(language, 'apk_summary')}",
        "",
        f"| {_label(language, 'field')} | {_label(language, 'value')} |",
        "| --- | --- |",
        f"| {_label(language, 'file')} | `{_md(apk.file_name)}` |",
        f"| {_label(language, 'size')} | `{_format_size(apk.file_size, language)}` |",
        f"| {_label(language, 'package')} | `{_md(apk.package_name)}` |",
        f"| {_label(language, 'app_name')} | `{_md(apk.app_name)}` |",
        f"| {_label(language, 'version')} | `{_md(apk.version_name)}` (`{_md(apk.version_code)}`) |",
        f"| {_label(language, 'sdk')} | {_label(language, 'min')} `{_md(apk.min_sdk)}`, {_label(language, 'target')} `{_md(apk.target_sdk)}`, {_label(language, 'compile')} `{_md(apk.compile_sdk)}` |",
        f"| MD5 | `{apk.hashes.md5}` |",
        f"| SHA1 | `{apk.hashes.sha1}` |",
        f"| SHA256 | `{apk.hashes.sha256}` |",
        "",
    ]


def _risk_summary(report: AnalysisReport, language: str) -> list[str]:
    counts = report.statistics.get("findings_by_severity", {}) if report.statistics else {}
    lines = [
        f"## {_label(language, 'risk_summary')}",
        "",
        f"| {_label(language, 'severity')} | {_label(language, 'count')} |",
        "| --- | ---: |",
        f"| {_label(language, 'high')} | {counts.get('high', 0)} |",
        f"| {_label(language, 'medium')} | {counts.get('medium', 0)} |",
        f"| {_label(language, 'low')} | {counts.get('low', 0)} |",
        f"| {_label(language, 'info')} | {counts.get('info', 0)} |",
        "",
    ]
    if report.findings:
        lines.extend([
            f"| {_label(language, 'severity')} | {_label(language, 'rule')} | {_label(language, 'evidence')} |",
            "| --- | --- | --- |",
            *[f"| {_md(_severity_label(item.severity, language))} | `{_md(item.id)}` | {_md(_finding_evidence(item, language))} |" for item in report.findings],
            "",
        ])
    else:
        lines.extend([_label(language, "no_risks"), ""])
    return lines


def _manifest_findings(report: AnalysisReport, language: str) -> list[str]:
    manifest = report.manifest
    return [
        f"## {_label(language, 'manifest_findings')}",
        "",
        f"| {_label(language, 'field')} | {_label(language, 'value')} |",
        "| --- | --- |",
        f"| {_label(language, 'application_class')} | `{_md(manifest.application_class)}` |",
        f"| {_label(language, 'debuggable')} | `{manifest.debuggable}` |",
        f"| {_label(language, 'allow_backup')} | `{manifest.allow_backup}` |",
        f"| {_label(language, 'cleartext_traffic')} | `{manifest.uses_cleartext_traffic}` |",
        f"| {_label(language, 'network_security_config')} | `{_md(manifest.network_security_config)}` |",
        f"| {_label(language, 'deep_links')} | `{len(manifest.deep_links)}` |",
        f"| {_label(language, 'provider_authorities')} | `{len(manifest.provider_authorities)}` |",
        "",
    ]


def _permissions(report: AnalysisReport, language: str) -> list[str]:
    lines = [f"## {_label(language, 'permissions')}", ""]
    if not report.permissions:
        lines.extend([_label(language, "no_permissions"), ""])
        return lines
    lines.extend([f"| {_label(language, 'level')} | {_label(language, 'permission')} | {_label(language, 'recommendation')} |", "| --- | --- | --- |"])
    for permission in report.permissions:
        recommendation = _permission_recommendation(permission.level, permission.recommendation, language)
        lines.append(f"| {_md(_severity_label(permission.level, language))} | `{_md(permission.name)}` | {_md(recommendation)} |")
    lines.append("")
    return lines


def _exported_components(report: AnalysisReport, language: str) -> list[str]:
    exported = _exported_components_list(report)
    lines = [f"## {_label(language, 'exported_components')}", ""]
    if not exported:
        lines.extend([_label(language, "no_exported"), ""])
        return lines
    lines.extend([f"| {_label(language, 'type')} | {_label(language, 'name')} | {_label(language, 'exported')} | {_label(language, 'permission')} |", "| --- | --- | --- | --- |"])
    for component in exported:
        lines.append(
            f"| {_md(component.type)} | `{_md(component.name)}` | `{component.exported}` | `{_md(component.permission)}` |"
        )
    lines.append("")
    return lines


def _strings(report: AnalysisReport, language: str) -> list[str]:
    urls = [item for item in report.strings if item.type == "url"]
    secrets = [item for item in report.strings if item.type in {"possible_secret", "jwt"}]
    network = [item for item in report.strings if item.type in {"url", "ip", "email"}]

    lines = [f"## {_label(language, 'network_artifacts')}", ""]
    lines.extend(_string_table(network[:100], empty=_label(language, "no_network"), language=language))
    lines.extend([f"## {_label(language, 'possible_secrets')}", ""])
    lines.extend(_string_table(secrets[:100], empty=_label(language, "no_secrets"), language=language))
    if len(urls) > 100 or len(secrets) > 100:
        lines.extend([f"> {_label(language, 'truncated')}", ""])
    return lines


def _certificate(report: AnalysisReport, language: str) -> list[str]:
    cert = report.certificate
    lines = [f"## {_label(language, 'certificate')}", ""]
    lines.extend([
        f"{_label(language, 'sig_schemes')}: `{', '.join(cert.schemes) if cert.schemes else _label(language, 'unknown')}`",
        "",
    ])
    if cert.certificates:
        lines.extend([f"| {_label(language, 'subject')} | {_label(language, 'issuer')} | {_label(language, 'valid_until')} | SHA256 |", "| --- | --- | --- | --- |"])
        for item in cert.certificates:
            lines.append(f"| {_md(item.subject)} | {_md(item.issuer)} | `{_md(item.not_valid_after)}` | `{_md(item.sha256)}` |")
        lines.append("")
    elif cert.signature_files:
        lines.extend([f"| {_label(language, 'signature_file')} | {_label(language, 'size')} | SHA256 |", "| --- | ---: | --- |"])
        for item in cert.signature_files:
            lines.append(f"| `{_md(item.path)}` | {item.size} | `{item.hashes.sha256}` |")
        lines.append("")
    for note in cert.notes:
        lines.append(f"- {note}")
    if cert.notes:
        lines.append("")
    return lines


def _native_libraries(report: AnalysisReport, language: str) -> list[str]:
    lines = [f"## {_label(language, 'native_libraries')}", ""]
    if not report.native_libraries:
        lines.extend([_label(language, "no_native"), ""])
        return lines
    lines.extend([f"| {_label(language, 'abi')} | {_label(language, 'library')} | {_label(language, 'size')} | {_label(language, 'stripped')} | SHA256 |", "| --- | --- | ---: | --- | --- |"])
    for item in report.native_libraries:
        lines.append(f"| `{_md(item.abi)}` | `{_md(item.name)}` | {item.size} | `{item.stripped}` | `{item.hashes.sha256}` |")
    lines.append("")
    return lines


def _fingerprints(report: AnalysisReport, language: str) -> list[str]:
    lines = [f"## {_label(language, 'sdk_fingerprints')}", ""]
    if report.sdks:
        lines.extend([f"| SDK | {_label(language, 'type')} | {_label(language, 'matched_patterns')} |", "| --- | --- | --- |"])
        for sdk in report.sdks:
            lines.append(f"| {_md(sdk.name)} | {_md(sdk.type)} | `{_md(', '.join(sdk.matched_patterns))}` |")
        lines.append("")
    else:
        lines.extend([_label(language, "no_sdks"), ""])

    lines.extend([f"## {_label(language, 'packer_fingerprints')}", ""])
    if report.packers:
        lines.extend([f"| {_label(language, 'packers')} | {_label(language, 'confidence')} | {_label(language, 'matched_patterns')} |", "| --- | --- | --- |"])
        for packer in report.packers:
            lines.append(f"| {_md(packer.name)} | {_md(packer.confidence)} | `{_md(', '.join(packer.matched_patterns))}` |")
        lines.append("")
    else:
        lines.extend([_label(language, "no_packers"), ""])
    return lines


def _recommendations(findings: list[Finding], language: str) -> list[str]:
    lines = [f"## {_label(language, 'recommendations')}", ""]
    recommendations = []
    seen = set()
    for finding in findings:
        recommendation = _finding_recommendation(finding, language)
        if recommendation not in seen:
            seen.add(recommendation)
            recommendations.append(recommendation)
    if not recommendations:
        lines.extend([_label(language, "no_recommendations"), ""])
        return lines
    for recommendation in recommendations:
        lines.append(f"- {recommendation}")
    lines.append("")
    return lines


def _string_table(items: list[StringFinding], empty: str, language: str) -> list[str]:
    if not items:
        return [empty, ""]
    lines = [f"| {_label(language, 'type')} | {_label(language, 'severity')} | {_label(language, 'value')} | {_label(language, 'source')} |", "| --- | --- | --- | --- |"]
    for item in items:
        lines.append(f"| {_md(item.type)} | {_md(_severity_label(item.severity, language))} | `{_md(item.value)}` | `{_md(item.source)}` |")
    lines.append("")
    return lines


def _md(value: object) -> str:
    if value is None:
        return ""
    return escape(str(value)).replace("|", "\\|").replace("\n", " ")


def _plain(value: object) -> str:
    if value is None:
        return ""
    return str(value).replace("\r", " ").replace("\n", " ").strip()


def _html(value: object) -> str:
    return escape(_plain(value), quote=True)


def _format_size(size: int, language: str = "zh") -> str:
    value = float(size)
    for unit in ("bytes", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            byte_unit = _label(language, "bytes")
            return f"{value:.1f} {unit}" if unit != "bytes" else f"{int(value)} {byte_unit}"
        value /= 1024
    return f"{size} {_label(language, 'bytes')}"


def _overall_verdict(report: AnalysisReport, language: str = "zh") -> str:
    counts = report.statistics.get("findings_by_severity", {}) if report.statistics else {}
    confidence = report.statistics.get("findings_by_confidence", {}) if report.statistics else {}
    if language == "zh":
        if counts.get("high", 0) and confidence.get("high", 0):
            return "存在高置信高危静态风险项，建议人工复核后再发布或分发。"
        if counts.get("high", 0):
            return "存在高危静态风险项，需结合业务上下文人工复核。"
        if counts.get("medium", 0):
            return "建议复核；当前未触发高危规则。"
        if report.errors:
            return "分析完成但存在解析说明，信任结果前请确认覆盖范围。"
        return "内置静态规则未发现主要风险。"
    if counts.get("high", 0) and confidence.get("high", 0):
        return "High-confidence high-risk findings were found; manual review is recommended before release or distribution."
    if counts.get("high", 0):
        return "High-risk findings were found; review them with app context."
    if counts.get("medium", 0):
        return "Review recommended; no high-risk rule fired."
    if report.errors:
        return "Analysis completed with parser notes; review coverage before trusting results."
    return "No major built-in static-analysis risk was detected."


def _join_names(values: list[str], language: str = "zh") -> str:
    cleaned = [_plain(value) for value in values if _plain(value)]
    return ", ".join(cleaned) if cleaned else _label(language, "none")


def _join_finding_drivers(findings: list[Finding], limit: int = 4, language: str = "zh") -> str:
    groups = _ranked_finding_groups(findings, limit)
    if not groups:
        return _label(language, "none")
    return ", ".join(f"{finding_id}={count}" for finding_id, count, _ in groups)


def _severity_rank(severity: str) -> int:
    return {"high": 0, "medium": 1, "low": 2, "info": 3}.get(severity, 9)


def _ranked_finding_groups(findings: list[Finding], limit: int) -> list[tuple[str, int, Finding]]:
    counts = Counter(item.id for item in findings)
    first_by_id: dict[str, Finding] = {}
    for finding in findings:
        first_by_id.setdefault(finding.id, finding)
    groups = [(finding_id, count, first_by_id[finding_id]) for finding_id, count in counts.items()]
    return sorted(groups, key=lambda item: (_severity_rank(item[2].severity), -item[1], item[0]))[:limit]


def _summary_list(title: str, items: list[str], language: str = "zh") -> list[str]:
    lines = [f"## {title}", ""]
    if not items:
        lines.extend([f"- {_label(language, 'none')}", ""])
        return lines
    for item in items:
        lines.append(f"- {_plain(item)}")
    lines.append("")
    return lines


def _format_top_findings(findings: list[Finding], limit: int = 10, language: str = "zh") -> list[str]:
    if not findings:
        return []

    output: list[str] = []
    for _, count, finding in _ranked_finding_groups(findings, limit):
        output.append(
            f"[{_severity_label(finding.severity, language)} / {_confidence_label(finding.confidence, language)}] "
            f"{_finding_title(finding, language)} ({count}) - {_finding_evidence(finding, language)}"
        )
    return output


def _group_deep_links(items: list[dict[str, str]]) -> list[dict[str, object]]:
    grouped: dict[str, dict[str, object]] = {}
    fields = (
        ("scheme", "schemes"),
        ("host", "hosts"),
        ("port", "ports"),
        ("path", "paths"),
        ("pathPrefix", "path_prefixes"),
        ("pathPattern", "path_patterns"),
        ("mimeType", "mime_types"),
    )
    for item in items:
        component = item.get("component") or "<unknown>"
        group = grouped.setdefault(component, {"component": component})
        for source_key, output_key in fields:
            value = item.get(source_key)
            if not value:
                continue
            values = group.setdefault(output_key, [])
            if isinstance(values, list) and value not in values:
                values.append(value)
    return list(grouped.values())


def _format_deep_link_group(item: dict[str, object]) -> str:
    route_parts = []
    for key, label in (
        ("schemes", "scheme"),
        ("hosts", "host"),
        ("ports", "port"),
        ("paths", "path"),
        ("path_prefixes", "pathPrefix"),
        ("path_patterns", "pathPattern"),
        ("mime_types", "mimeType"),
    ):
        values = item.get(key)
        if isinstance(values, list) and values:
            route_parts.append(f"{label}={', '.join(str(value) for value in values)}")
    route = "; ".join(route_parts) if route_parts else "<any>"
    return f"{item.get('component', '<unknown>')} ({route})"


def _top_recommendations(findings: list[Finding], limit: int = 8, language: str = "zh") -> list[str]:
    recommendations: list[str] = []
    seen: set[str] = set()
    for finding in sorted(findings, key=lambda item: _severity_rank(item.severity)):
        recommendation = _finding_recommendation(finding, language)
        if recommendation not in seen:
            seen.add(recommendation)
            recommendations.append(recommendation)
        if len(recommendations) >= limit:
            break
    return recommendations


def _exported_components_list(report: AnalysisReport):
    return [item for item in report.manifest.components if item.externally_reachable]


def _html_card(label: str, value: object, tone: str) -> str:
    return f'<div class="card {_html(tone)}"><span>{_html(label)}</span><strong>{_html(value)}</strong></div>'


def _html_key_values(items: list[tuple[str, object]]) -> str:
    rows = "".join(f"<tr><th>{_html(key)}</th><td><code>{_html(value)}</code></td></tr>" for key, value in items)
    return f"<table>{rows}</table>"


def _html_section(title: str, body: str, open_section: bool) -> str:
    open_attr = " open" if open_section else ""
    return f'<details class="section"{open_attr}><summary>{_html(title)}</summary>{body}</details>'


def _html_findings(findings: list[Finding], language: str = "zh") -> str:
    if not findings:
        return f"<p class=\"muted\">{_html(_label(language, 'no_risks'))}</p>"
    rows = []
    for finding in findings:
        evidence = _finding_evidence(finding, language)
        review_hint = _finding_review_hint(finding, language)
        search_text = f"{finding.severity} {finding.confidence} {finding.id} {evidence} {review_hint}".lower()
        rows.append(
            f"<tr data-finding-row data-severity=\"{_html(finding.severity)}\" data-search=\"{_html(search_text)}\">"
            f"<td><span class=\"badge\">{_html(_severity_label(finding.severity, language))}</span></td>"
            f"<td>{_html(_confidence_label(finding.confidence, language))}</td>"
            f"<td><code>{_html(finding.id)}</code></td>"
            f"<td>{_html(evidence)}</td>"
            f"<td>{_html(review_hint)}</td>"
            "</tr>"
        )
    controls = (
        '<div class="controls">'
        '<div class="control">'
        f'<label for="finding-search">{_html(_label(language, "search_findings"))}</label>'
        f'<input id="finding-search" type="search" placeholder="{_html(_label(language, "search_placeholder"))}">'
        '</div>'
        '<div class="control">'
        f'<label for="finding-severity">{_html(_label(language, "severity_filter"))}</label>'
        '<select id="finding-severity">'
        f'<option value="">{_html(_label(language, "all"))}</option>'
        f'<option value="high">{_html(_label(language, "high"))}</option>'
        f'<option value="medium">{_html(_label(language, "medium"))}</option>'
        f'<option value="low">{_html(_label(language, "low"))}</option>'
        f'<option value="info">{_html(_label(language, "info"))}</option>'
        '</select>'
        '</div>'
        f'<div class="finding-meta">{_html(_label(language, "matching_findings"))}: <span id="finding-count">{len(findings)}/{len(findings)}</span></div>'
        '</div>'
        f'<p id="finding-empty" class="muted hidden">{_html(_label(language, "no_matching_findings"))}</p>'
    )
    table = (
        f"<table><tr><th>{_html(_label(language, 'severity'))}</th><th>{_html(_label(language, 'confidence'))}</th>"
        f"<th>{_html(_label(language, 'rule'))}</th><th>{_html(_label(language, 'evidence'))}</th>"
        f"<th>{_html(_label(language, 'review_hint'))}</th></tr>" + "".join(rows) + "</table>"
    )
    return controls + table


def _html_list(items: list[str], empty: str) -> str:
    if not items:
        return f'<p class="muted">{_html(empty)}</p>'
    return "<ul>" + "".join(f"<li><code>{_html(item)}</code></li>" for item in items) + "</ul>"


def _html_filter_script() -> str:
    return """<script>
(() => {
  const search = document.getElementById('finding-search');
  const severity = document.getElementById('finding-severity');
  const count = document.getElementById('finding-count');
  const empty = document.getElementById('finding-empty');
  const rows = Array.from(document.querySelectorAll('[data-finding-row]'));
  function applyFilters() {
    const query = (search?.value || '').trim().toLowerCase();
    const selectedSeverity = severity?.value || '';
    let visible = 0;
    for (const row of rows) {
      const matchesSeverity = !selectedSeverity || row.dataset.severity === selectedSeverity;
      const matchesQuery = !query || (row.dataset.search || '').includes(query);
      const show = matchesSeverity && matchesQuery;
      row.hidden = !show;
      if (show) visible += 1;
    }
    if (count) count.textContent = `${visible}/${rows.length}`;
    if (empty) empty.classList.toggle('hidden', visible !== 0);
  }
  search?.addEventListener('input', applyFilters);
  severity?.addEventListener('change', applyFilters);
  applyFilters();
})();
</script>"""


def _normalize_language(language: str) -> str:
    normalized = (language or "zh").lower()
    return normalized if normalized in SUPPORTED_LANGUAGES else "zh"


def _label(language: str, key: str) -> str:
    lang = _normalize_language(language)
    return LABELS[lang].get(key, LABELS["en"].get(key, key))


def _severity_label(severity: str, language: str) -> str:
    normalized = (severity or "").lower()
    if normalized in {"high", "medium", "low", "info"}:
        return _label(language, normalized)
    if normalized == "sensitive":
        return "敏感" if language == "zh" else "Sensitive"
    if normalized == "normal":
        return "普通" if language == "zh" else "Normal"
    return severity.upper() if language == "en" else severity


def _confidence_label(confidence: str, language: str) -> str:
    normalized = (confidence or "medium").lower()
    if language == "zh":
        return {"high": "高置信", "medium": "中置信", "low": "低置信"}.get(normalized, confidence)
    return {"high": "High", "medium": "Medium", "low": "Low"}.get(normalized, confidence.title())


def _finding_title(finding: Finding, language: str) -> str:
    if language == "zh":
        return FINDING_TITLES_ZH.get(finding.id, finding.title)
    return finding.title


def _finding_recommendation(finding: Finding, language: str) -> str:
    if language == "zh":
        return FINDING_RECOMMENDATIONS_ZH.get(finding.id, finding.recommendation)
    return finding.recommendation


def _finding_review_hint(finding: Finding, language: str) -> str:
    if language == "zh":
        return FINDING_REVIEW_HINTS_ZH.get(finding.id, finding.review_hint or "人工复核该发现项是否可被真实触发。")
    return finding.review_hint or "Manually review whether this finding is reachable in the target app context."


def _permission_recommendation(level: str, recommendation: str, language: str) -> str:
    if language != "zh":
        return recommendation
    normalized = (level or "").lower()
    if normalized == "high":
        return "确认该高危权限是否为核心功能必需；不必要时移除，并在隐私说明中明确用途。"
    if normalized == "sensitive":
        return "仅在功能必需时保留，优先使用更低敏感度的替代能力。"
    return "仅在功能确实需要时保留。"


def _finding_evidence(finding: Finding, language: str) -> str:
    if language != "zh":
        return finding.evidence
    evidence = finding.evidence
    if finding.id in {
        "exported-component",
        "exported-provider",
        "exported-provider-partial-permission",
        "exported-provider-grant-uri",
        "exported-service",
        "exported-receiver",
        "exported-activity",
        "exported-deep-link-activity",
        "exported-protected-component",
        "exported-media-component",
        "exported-quick-settings-tile",
        "exported-autofill-service",
        "exported-documents-provider",
        "exported-file-provider",
        "exported-share-target-activity",
        "exported-file-handler-activity",
        "exported-custom-tabs-service",
        "exported-car-service",
        "exported-widget-receiver",
        "implicit-exported-component",
    }:
        evidence = evidence.replace(" is explicitly exported.", " 显式导出。")
        evidence = evidence.replace(" is exported without permission.", " 导出且未配置权限保护。")
        evidence = evidence.replace(" is exported with permission ", " 导出，并受权限保护：")
        evidence = evidence.replace(" is exported with read/write permission split.", " 导出，并使用 read/write 权限分离。")
        evidence = evidence.replace(" is exported with grantUriPermissions enabled.", " 导出，并启用了 grantUriPermissions。")
        evidence = evidence.replace(" exposes deep link intent filters without permission.", " 暴露 Deep Link intent-filter 且未配置权限保护。")
        evidence = evidence.replace(" exposes standard media control actions.", " 暴露标准媒体控制动作。")
        evidence = evidence.replace(" is exported for Quick Settings tile binding.", " 作为快捷设置 Tile 服务导出。")
        evidence = evidence.replace(" is exported for Autofill binding.", " 作为 Autofill 服务导出。")
        evidence = evidence.replace(" is exported as a DocumentsProvider.", " 作为 DocumentsProvider 导出。")
        evidence = evidence.replace(" accepts external share intents.", " 接收外部分享 Intent。")
        evidence = evidence.replace(" accepts file/content input.", " 接收 file/content 外部输入。")
        evidence = evidence.replace(" is exported for Custom Tabs.", " 作为 Custom Tabs 服务导出。")
        evidence = evidence.replace(" is exported for car integration.", " 作为车载集成服务导出。")
        evidence = evidence.replace(" is exported for app widget updates.", " 作为 App Widget 更新 Receiver 导出。")
        evidence = evidence.replace(" has intent filters and no explicit exported value.", " 包含 intent-filter 且未显式设置 exported。")
        evidence = evidence.replace(
            " is has intent-filter and no explicit exported value.",
            " 包含 intent-filter 且未显式设置 exported。",
        )
    return evidence
