from __future__ import annotations


FINDING_TITLES_ZH = {
    "android-debuggable-enabled": "启用了 Debuggable",
    "android-allow-backup-enabled": "允许 ADB 备份",
    "cleartext-traffic-enabled": "允许明文网络流量",
    "exported-component": "导出组件",
    "exported-provider": "导出 Provider 未受权限保护",
    "exported-provider-partial-permission": "导出 Provider 使用读写权限分离",
    "exported-provider-grant-uri": "导出 Provider 允许 URI 授权",
    "exported-service": "导出 Service 未受权限保护",
    "exported-receiver": "导出 Receiver 未受权限保护",
    "exported-activity": "导出 Activity 未受权限保护",
    "exported-deep-link-activity": "导出 Deep Link Activity",
    "exported-protected-component": "受权限保护的导出组件",
    "exported-media-component": "导出媒体控制组件",
    "exported-quick-settings-tile": "导出快捷设置 Tile 服务",
    "exported-autofill-service": "导出 Autofill 服务",
    "exported-documents-provider": "导出 DocumentsProvider",
    "exported-file-provider": "导出 FileProvider 未受权限保护",
    "exported-share-target-activity": "导出分享入口 Activity",
    "exported-file-handler-activity": "导出文件处理 Activity",
    "exported-custom-tabs-service": "导出 Custom Tabs 服务",
    "exported-car-service": "导出车载集成服务",
    "exported-widget-receiver": "导出 App Widget Receiver",
    "implicit-exported-component": "隐式导出组件",
    "high-risk-permission": "高危权限",
    "hardcoded-secret": "疑似硬编码密钥",
    "http-url-found": "发现 HTTP 明文 URL",
    "debug-certificate": "Debug 证书",
}


FINDING_RECOMMENDATIONS_ZH = {
    "android-debuggable-enabled": "Release 构建中关闭 android:debuggable。",
    "android-allow-backup-enabled": "除非确有必要且已做保护，否则设置 android:allowBackup=\"false\"。",
    "cleartext-traffic-enabled": "使用 HTTPS，并通过 network security config 限制明文流量。",
    "exported-component": "明确设置 android:exported，并为可被外部访问的组件增加权限保护。",
    "exported-provider": "设置 android:exported=\"false\"，或使用 signature 级权限保护 Provider。",
    "exported-provider-partial-permission": "确认 readPermission 和 writePermission 的保护级别足以保护暴露的数据和操作。",
    "exported-provider-grant-uri": "复核 Provider path 范围，只对预期文件或记录授予 URI 权限。",
    "exported-service": "设置 android:exported=\"false\"，或为 Service 增加 signature 级权限。",
    "exported-receiver": "限制 Receiver 暴露面，校验外部广播，或为外部广播增加权限要求。",
    "exported-activity": "除非该 Activity 是公开入口，否则设置 android:exported=\"false\"，并校验所有 Intent 输入。",
    "exported-deep-link-activity": "校验所有 Deep Link 参数，敏感流程必须鉴权，并尽量限制 exported 暴露面。",
    "exported-protected-component": "确认权限 protectionLevel，只有确需外部访问时才保持 exported。",
    "exported-media-component": "确认该组件只处理标准媒体控制 Intent，并校验外部输入。",
    "exported-quick-settings-tile": "确认 Tile 服务只响应系统绑定和明确用户操作，不在点击前执行敏感逻辑。",
    "exported-autofill-service": "确认服务受 Autofill 框架权限保护，并校验所有填充请求。",
    "exported-documents-provider": "确认文档根目录、URI grant 和访问控制只暴露用户授权文件。",
    "exported-file-provider": "除非确需公开访问，否则设置 android:exported=\"false\"，并限制 provider paths 和 URI grant。",
    "exported-share-target-activity": "校验分享 MIME 类型、URI 权限、文件大小和内容解析逻辑。",
    "exported-file-handler-activity": "校验 URI scheme、MIME 类型、文件大小和解析器行为。",
    "exported-custom-tabs-service": "确认 Custom Tabs 暴露的方法不会泄露浏览状态或触发特权操作。",
    "exported-car-service": "校验 Android Auto / 车载入口，避免无用户确认执行敏感行为。",
    "exported-widget-receiver": "校验 Widget 广播 action 和 extras，忽略非预期外部广播。",
    "implicit-exported-component": "显式设置 android:exported；除非确需外部访问，否则设置为 false。",
    "high-risk-permission": "确认该权限是否为核心功能必需；不必要时移除或改用更低敏感度能力。",
    "hardcoded-secret": "不要在 APK 中硬编码密钥；确认泄露后应轮换凭据并迁移到服务端。",
    "http-url-found": "优先使用 HTTPS，移除无用的调试、测试或明文接口地址。",
    "debug-certificate": "Release 包应使用受保护的正式签名证书。",
}


FINDING_REVIEW_HINTS_ZH = {
    "android-debuggable-enabled": "确认该 APK 是否为 Release 构建；正式分发包不应启用 debuggable。",
    "android-allow-backup-enabled": "复核敏感本地数据是否可能被备份或恢复，并结合目标 Android 版本确认行为。",
    "cleartext-traffic-enabled": "检查 network security config 和运行时接口，确认生产环境是否存在可达明文流量。",
    "exported-provider": "复核 Provider authorities、path permissions、grantUriPermissions 和 query/insert/update/delete 处理逻辑。",
    "exported-provider-partial-permission": "复核 readPermission/writePermission 的 protectionLevel，确认不存在未受保护的读写操作。",
    "exported-provider-grant-uri": "复核 path-permission、meta-data 和 provider paths，确认 URI grant 不会暴露过宽的私有数据。",
    "exported-service": "复核 Service 入口、Intent 处理、Binder 暴露面以及调用方鉴权。",
    "exported-receiver": "复核接收的广播 action，确保不可信 extras 不能触发敏感行为。",
    "exported-activity": "确认该 Activity 是否有意作为公开入口，并校验所有 Intent extras 和 data URI。",
    "exported-deep-link-activity": "复核 scheme、host、path 过滤规则、鉴权要求和所有 Deep Link 参数校验。",
    "exported-media-component": "复核 Intent 处理代码，确保只接受预期的标准媒体控制动作。",
    "exported-protected-component": "确认权限 protectionLevel；normal 或 dangerous 级权限可能不足以保护敏感导出组件。",
    "exported-quick-settings-tile": "复核 Tile 点击处理，确保没有用户意图时不会执行敏感操作。",
    "exported-autofill-service": "复核 Autofill 数据集处理，确认只有可信框架调用能访问敏感数据。",
    "exported-documents-provider": "复核 query/openDocument/deleteDocument 处理逻辑，确认访问范围受用户授权限制。",
    "exported-file-provider": "复核 provider paths、URI grant、MIME 处理以及所有 openFile/openAssetFile 路径。",
    "exported-share-target-activity": "复核 ACTION_SEND/ACTION_SEND_MULTIPLE 处理，拒绝非预期 MIME 类型或超大输入。",
    "exported-file-handler-activity": "复核 ACTION_VIEW 对 file/content URI 的处理，确认解析外部内容不会触发不安全文件访问。",
    "exported-custom-tabs-service": "复核 Custom Tabs 绑定行为，确认调用方不能访问敏感浏览器内部状态。",
    "exported-car-service": "复核 Android Auto 会话处理、导航 Intent 和对调用方的假设。",
    "exported-widget-receiver": "复核 Widget action 处理，忽略非预期广播或不可信 extras。",
    "implicit-exported-component": "确认目标平台行为，并显式设置 android:exported 以避免暴露面不一致。",
    "high-risk-permission": "确认权限是否为核心功能必需，并通过运行时授权流程或功能开关限制使用。",
    "hardcoded-secret": "确认该值是否为有效凭据或 Token；如确认泄露，应立即轮换。",
    "http-url-found": "确认该 URL 是否在生产代码中可达；静态字符串可能包含历史、插件或测试端点。",
    "debug-certificate": "确认 APK 是否不是 Release 产物；生产分发包不应使用 Debug 证书。",
}
